[pytest]  
testpaths = tests
pythonpath = .
asyncio_mode = auto
addopts =
    -v
    --strict-markers
    --tb=short
    --cov=application
    --cov=domain
    --cov=infrastructure
    --cov-report=term-missing
    --cov-report=html
markers =
    unit: Pruebas unitarias con mocks
    integration: Pruebas de integración con BD